Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -42,17 +42,17 @@ jobs:
             ls -l ~
 
       - checkout
-      - run:
+      # - run:
       # Our primary container isn't MYSQL so run a sleep command until it's ready.
-          name: Waiting for MySQL to be ready
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z 127.0.0.1 3306 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for MySQL && exit 1
+          # name: Waiting for MySQL to be ready
+          # command: |
+            # for i in `seq 1 10`;
+            # do
+              # nc -z 127.0.0.1 3306 && echo Success && exit 0
+              # echo -n .
+              # sleep 1
+            # done
+            # echo Failed waiting for MySQL && exit 1
       # - run:
           # name: Install MySQL CLI; Import dummy data; run an example query
           # command: |
